name: Build ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-24.04
    steps:
      - uses: jlumbroso/free-disk-space@3e0187054f9c4bc1f55a743792872df36b2d88e0
        with:
          tool-cache: true
      - uses: actions/checkout@v4
      - name: install livefs-editor
        run: |
          git clone https://github.com/mwhudson/livefs-editor
          cd livefs-editor/
          sudo python3 -m pip install . --break-system-packages
          sudo apt install -y xorriso squashfs-tools python3-debian mount
      - name: Fetch base ISO
        id: download
        uses: mercury233/action-cache-download-file@v1.0.0
        with:
          url: 'https://releases.ubuntu.com/24.04.3/ubuntu-24.04.3-desktop-amd64.iso'
          destination: ${{ github.workspace }}
          filename: 'ubuntu-24.04.3-desktop-amd64.iso'
      - name: Build Kramden ISO
        run: |
          cd noble
          echo ${{ github.workspace }}
          echo "list ISO"
          ls -ltrh ${{ steps.download.outputs.filepath }} || true
          echo "list dir"
          ls -ltrh ${{ github.workspace }} || true
          sudo ./kramden.sh ${{ steps.download.outputs.filepath }}
      - name: Save ISO
        uses: actions/upload-artifact@v4
        with:
          name: kramden-iso
          path: ${{ github.workspace }}/kramden*.iso
          retention-days: 5
