name: Build ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-24.04
    steps:
      - name: release-vars
        id: release-vars
        run: |
          sudo apt install -y curl jq
          echo URL=$(echo https://releases.ubuntu.com/$(curl -sL https://releases.ubuntu.com/streams/v1/com.ubuntu.releases:ubuntu.json | jq '.products["com.ubuntu.releases:ubuntu:desktop:24.04:amd64"].versions["24.04.3"].items.iso.path' | sed 's/\"//g')) >> "$GITHUB_OUTPUT"
          echo FILENAME=$(echo $(curl -sL https://releases.ubuntu.com/streams/v1/com.ubuntu.releases:ubuntu.json | jq '.products["com.ubuntu.releases:ubuntu:desktop:24.04:amd64"].versions["24.04.3"].items.iso.path' | sed 's/\"//g' | awk -F / '{print $2}')) >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - name: install livefs-editor
        run: |
          git clone https://github.com/mwhudson/livefs-editor
          cd livefs-editor/
          python3 -m pip install .
      - name: Fetch base ISO
        id: download
        uses: mercury233/action-cache-download-file@v1
        with:
          url: ${{ steps.release-vars.outputs.URL }}
          destination: 'downloads'
          filename: ${{ steps.release-vars.outputs.FILENAME }}
      - name: Build Kramden ISO
        run: |
          sudo apt install -y ubuntu-dev-tools wget
          cd noble
          ./kramden.sh ${{ steps.download.outputs.filepath }}
      - name: Save ISO
        uses: actions/upload-artifact@v4
        with:
          name: kramden-iso
          path: kramden*.iso
