name: Build ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: install livefs-editor
        run: |
          git clone https://github.com/mwhudson/livefs-editor
          cd livefs-editor/
          sudo python3 -m pip install . --break-system-packages
          sudo apt install -y xorriso squashfs-tools python3-debian mount
      - name: Fetch base ISO
        id: download
        uses: mercury233/action-cache-download-file@v1.0.0
        with:
          url: 'https://releases.ubuntu.com/24.04.3/ubuntu-24.04.3-desktop-amd64.iso'
          destination: 'downloads'
          filename: 'ubuntu-24.04.3-desktop-amd64.iso'
        run: |
          echo "ISOPATH=$PWD" >> $GITHUB_ENV
      - name: Build Kramden ISO
        run: |
          cd noble
          echo ${{ env.ISOPATH }}
          echo "list ISO"
          ls -ltrh ${{ env.ISOPATH }}/${{ steps.download.outputs.filepath }} || true
          echo "list dir"
          ls -ltrh ${{ env.ISOPATH }} || true
          #sudo ./kramden.sh ${{ env.ISOPATH }}/${{ steps.download.outputs.filepath }}
          mv kramden*.iso ${{ env.ISOPATH }}/
      - name: Save ISO
        uses: actions/upload-artifact@v4
        with:
          name: kramden-iso
          path: ${{ env.ISOPATH }}/kramden*.iso
