name: Build ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: install livefs-editor
        run: |
          git clone https://github.com/mwhudson/livefs-editor
          cd livefs-editor/
          python3 -m pip install .
      - name: Fetch base ISO
        uses: sozo-design/curl@v1.0.2
        with:
          args: -O ubuntu-24.04.2-desktop-amd64.iso -sL https://releases.ubuntu.com/24.04.2/ubuntu-24.04.2-desktop-amd64.iso
      - name: Build Kramden ISO
        run: |
          cd noble
          ./kramden.sh ubuntu-24.04.2-desktop-amd64.iso
      - name: Save ISO
        uses: actions/upload-artifact@v4
        with:
          name: kramden-iso
          path: kramden*.iso
